package event

const MESSAGE_CREATED = "MESSAGE_CREATED"
const MESSAGE_UPDATED = "MESSAGE_UPDATED"
const MESSAGE_DELETED = "MESSAGE_DELETED"
const GIT_PUSHED = "GIT_PUSHED"
const GIT_PR_CREATED = "GIT_PR_CREATED"
const GIT_PR_CLOSED = "GIT_PR_CLOSED"
const GIT_PR_MERGED = "GIT_PR_MERGED"
