version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser"]

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/tbson/simplepm"
