services:
    simplepm_db:
        container_name: simplepm_db
        image: 'postgres:16.4-alpine3.20'
        environment:
            PGUSER: ${POSTGRES_USER}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${POSTGRES_EXPOSE_PORT}:${POSTGRES_PORT}'
        volumes:
            # - ./volumes/db/sql/ext.sql:/docker-entrypoint-initdb.d/ext.sql
            - ./volumes/db/dbdata:/var/lib/postgresql/data/:delegated
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 3s
            timeout: 3s
            retries: 10

    simplepm_nosql:
        image: scylladb/scylla:6.2
        container_name: simplepm_nosql
        ports:
            - "9042:9042"   # CQL
            # - "9180:9180"   # Scylla Manager (if needed)
        volumes:
            - ./volumes/scylladb/data:/var/lib/scylla
            - ./volumes/scylladb/logs:/var/log/scylla
            - ./volumes/scylladb/migration:/migration

    simplepm_backend:
        container_name: simplepm_backend
        build:
            context: ../backend
            dockerfile: ../docker/dockerfiles/backend
        volumes:
            - ../backend:/code:delegated
        environment:
            GOPATH: /code/
            DEBUG: ${DEBUG}
            SECRET_KEY: ${SECRET_KEY}
            TIME_ZONE: ${TIME_ZONE}
            APP_NAME: ${APP_NAME}
            DEFAULT_ADMIN_EMAIL: ${DEFAULT_ADMIN_EMAIL}
            ADMIN_TEANT_UID: ${ADMIN_TEANT_UID}
            ADMIN_TEANT_TITLE: ${ADMIN_TEANT_TITLE}

            TEST_TEANT_UID: ${TEST_TEANT_UID}
            TETS_TEANT_TITLE: ${TETS_TEANT_TITLE}
            TEST_USER_EMAIL_ADMIN: ${TEST_USER_EMAIL_ADMIN}
            TEST_USER_EMAIL_STAFF: ${TEST_USER_EMAIL_STAFF}
            TEST_USER_EMAIL_OWNER: ${TEST_USER_EMAIL_OWNER}
            TEST_USER_EMAIL_MANAGER: ${TEST_USER_EMAIL_MANAGER}
            TEST_USER_EMAIL_USER: ${TEST_USER_EMAIL_USER}
            TEST_USER_PASSWORD: ${TEST_USER_PASSWORD}

            PROTOCOL: "https"
            DOMAIN: ${DOMAIN}
            BASE_URL: 'https://${DOMAIN}'

            ACCESS_TOKEN_LIFETIME: ${ACCESS_TOKEN_LIFETIME}
            ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
            REFRESH_TOKEN_LIFETIME: ${REFRESH_TOKEN_LIFETIME}
            REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}

            DB_HOST: ${POSTGRES_HOST}
            DB_PORT: ${POSTGRES_PORT}
            DB_USER: ${POSTGRES_USER}
            DB_NAME: ${POSTGRES_DB}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_URL: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable'
            DB_URL_TEST: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}_test?sslmode=disable'
            DB_URL_ATLAS: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}_atlas?sslmode=disable'
            DB_URL_ATLAS_TEST: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}_atlas_test?sslmode=disable'

            NOSQL_HOST: ${SCYLLADB_HOST}
            NOSQL_PORT: ${SCYLLADB_PORT}

            EMAIL_FROM: ${EMAIL_FROM}
            EMAIL_HOST: ${EMAIL_HOST}
            EMAIL_PORT: ${EMAIL_PORT}
            EMAIL_HOST_USER: ${EMAIL_HOST_USER}
            EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
            EMAIL_USE_TLS: ${EMAIL_USE_TLS}

            S3_ACCOUNT_ID: ${S3_ACCOUNT_ID}
            S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
            S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
            S3_BUCKET_NAME: ${S3_BUCKET_NAME}
            S3_REGION: ${S3_REGION}
            S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}

            SENTRY_DSN: ${SENTRY_DSN}

            CENTRIFUGO_CLIENT_SECRET: ${CENTRIFUGO_CLIENT_SECRET}
            CENTRIFUGO_API_KEY: ${CENTRIFUGO_API_KEY}
            CENTRIFUGO_API_ENDPOINT: ${CENTRIFUGO_API_ENDPOINT}
            CENTRIFUGO_JWT_LIFE_SPAN: ${CENTRIFUGO_JWT_LIFE_SPAN}

            QUEUE_BACKEND: ${QUEUE_BACKEND}

            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

            MSG_PAGE_SIZE: ${MSG_PAGE_SIZE}

            GITHUB_APP_PUBLIC_LINK: ${GITHUB_APP_PUBLIC_LINK}
            GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
            GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
            GITHUB_PRIVATE_KEY: ${GITHUB_PRIVATE_KEY}

            GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
            GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}
        ports:
            - '4000:4000'
        depends_on:
            simplepm_db:
                condition: service_healthy
        tty: true
        command: ${DOCKER_COMMAND}

    simplepm_frontend:
        container_name: simplepm_frontend
        build:
            context: ../frontend
            dockerfile: ../docker/dockerfiles/frontend
        volumes:
            - ../frontend:/code:delegated
            - /code/node_modules
        ports:
            - '3000:3000'
        tty: true

    simplepm_nginx:
        container_name: simplepm_nginx
        build:
            context: ./
            dockerfile: ./dockerfiles/nginx
        restart: always
        volumes:
            - ./volumes/nginx/conf:/etc/nginx/conf.d
            - ${SSL_PATH}:/resource/ssl
            - ../backend/public/:/resource/public
        ports:
            - '443:443'
        depends_on:
            - simplepm_backend

    # simplepm_socket:
    #    container_name: simplepm_socket
    #    image: centrifugo/centrifugo:v5.4
    #    volumes:
    #        - ./volumes/centrifugo/config.json:/centrifugo/config.json
    #    command: centrifugo -c config.json
    #    ports:
    #        - 8000:8000
    #    ulimits:
    #        nofile:
    #            soft: 65535
    #            hard: 65535
